name: nihongogoi2
description: Vocabulary helper app for CEAO Nihongo level 2

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  sqflite:
  path:
  image:
  path_provider:
  downloads_path_provider_28:
  permission_handler:
  open_file:
  flutter_local_notifications:
  confetti:
  flame:
  chips_choice:
  progress_dialog:
  flutter_gifimage:
  painter:
  devtools_server:
  dwds:
  flutter_html:
  cupertino_icons:
  flutter_launcher_icons:

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter


flutter_icons:
  ios: true
  android: true
  image_path_android: "assets/launcher/nihongo2.png"
  image_path_ios: "assets/launcher/nihongo2.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: KanjiStrokeOrders_v4
      fonts:
        - asset: assets/fonts/KanjiStrokeOrders_v4.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/nihongo_goi_2.db
    - assets/nihongo_goi_lessons.db
    - assets/background.jpg
    - assets/ost.mp3
    - assets/launcher/nihongo2.png
    - assets/gifs/cat_1.gif
    - assets/gifs/cat_2.gif
    - assets/gifs/cat_3.gif
    - assets/gifs/cat_4.gif
    - assets/gifs/cat_5.gif
    - assets/gifs/cat_6.gif
    - assets/gifs/cat_7.gif
    - assets/gifs/cat_8.gif
    - assets/gifs/cat_9.gif
    - assets/gifs/cat_10.gif
  #   - images/a_dot_ham.jpeg
