name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
        shell: bash
        working-directory: .
      - run: flutter create .
        shell: bash
        working-directory: .
      - uses: erickzanardo/flutter-gh-pages@v2
